//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientViVuTraVinh.serviceHinhAnh {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonResponseOfListOfHinhAnh", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class JsonResponseOfListOfHinhAnh : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientViVuTraVinh.serviceHinhAnh.HinhAnh[] DataField;
        
        private int StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClientViVuTraVinh.serviceHinhAnh.HinhAnh[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HinhAnh", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class HinhAnh : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DuongDanField;
        
        private System.Nullable<System.DateTime> NgayTaoField;
        
        private System.Nullable<int> NguoiTaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientViVuTraVinh.serviceHinhAnh.TaiKhoan TaiKhoanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DuongDan {
            get {
                return this.DuongDanField;
            }
            set {
                if ((object.ReferenceEquals(this.DuongDanField, value) != true)) {
                    this.DuongDanField = value;
                    this.RaisePropertyChanged("DuongDan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> NgayTao {
            get {
                return this.NgayTaoField;
            }
            set {
                if ((this.NgayTaoField.Equals(value) != true)) {
                    this.NgayTaoField = value;
                    this.RaisePropertyChanged("NgayTao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> NguoiTao {
            get {
                return this.NguoiTaoField;
            }
            set {
                if ((this.NguoiTaoField.Equals(value) != true)) {
                    this.NguoiTaoField = value;
                    this.RaisePropertyChanged("NguoiTao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ClientViVuTraVinh.serviceHinhAnh.TaiKhoan TaiKhoan {
            get {
                return this.TaiKhoanField;
            }
            set {
                if ((object.ReferenceEquals(this.TaiKhoanField, value) != true)) {
                    this.TaiKhoanField = value;
                    this.RaisePropertyChanged("TaiKhoan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaiKhoan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TaiKhoan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDangNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoDienThoaiField;
        
        private System.Nullable<int> RoleField;
        
        private System.Nullable<int> StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenDangNhap {
            get {
                return this.TenDangNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDangNhapField, value) != true)) {
                    this.TenDangNhapField = value;
                    this.RaisePropertyChanged("TenDangNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SoDienThoai {
            get {
                return this.SoDienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoDienThoaiField, value) != true)) {
                    this.SoDienThoaiField = value;
                    this.RaisePropertyChanged("SoDienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonResponseOfString", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class JsonResponseOfString : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        private int StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonResponseOfBoolean", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class JsonResponseOfBoolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private bool DataField;
        
        private int StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="serviceHinhAnh.HinhAnhServiceSoap")]
    public interface HinhAnhServiceSoap {
        
        // CODEGEN: Generating message contract since element name indexResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/index", ReplyAction="*")]
        ClientViVuTraVinh.serviceHinhAnh.indexResponse index(ClientViVuTraVinh.serviceHinhAnh.indexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/index", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceHinhAnh.indexResponse> indexAsync(ClientViVuTraVinh.serviceHinhAnh.indexRequest request);
        
        // CODEGEN: Generating message contract since element name DuongDan from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/store", ReplyAction="*")]
        ClientViVuTraVinh.serviceHinhAnh.storeResponse store(ClientViVuTraVinh.serviceHinhAnh.storeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/store", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceHinhAnh.storeResponse> storeAsync(ClientViVuTraVinh.serviceHinhAnh.storeRequest request);
        
        // CODEGEN: Generating message contract since element name f from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uploadFile", ReplyAction="*")]
        ClientViVuTraVinh.serviceHinhAnh.uploadFileResponse uploadFile(ClientViVuTraVinh.serviceHinhAnh.uploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uploadFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceHinhAnh.uploadFileResponse> uploadFileAsync(ClientViVuTraVinh.serviceHinhAnh.uploadFileRequest request);
        
        // CODEGEN: Generating message contract since element name DuongDan from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update", ReplyAction="*")]
        ClientViVuTraVinh.serviceHinhAnh.updateResponse update(ClientViVuTraVinh.serviceHinhAnh.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceHinhAnh.updateResponse> updateAsync(ClientViVuTraVinh.serviceHinhAnh.updateRequest request);
        
        // CODEGEN: Generating message contract since element name deleteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete", ReplyAction="*")]
        ClientViVuTraVinh.serviceHinhAnh.deleteResponse delete(ClientViVuTraVinh.serviceHinhAnh.deleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceHinhAnh.deleteResponse> deleteAsync(ClientViVuTraVinh.serviceHinhAnh.deleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="index", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceHinhAnh.indexRequestBody Body;
        
        public indexRequest() {
        }
        
        public indexRequest(ClientViVuTraVinh.serviceHinhAnh.indexRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class indexRequestBody {
        
        public indexRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="indexResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceHinhAnh.indexResponseBody Body;
        
        public indexResponse() {
        }
        
        public indexResponse(ClientViVuTraVinh.serviceHinhAnh.indexResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class indexResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceHinhAnh.JsonResponseOfListOfHinhAnh indexResult;
        
        public indexResponseBody() {
        }
        
        public indexResponseBody(ClientViVuTraVinh.serviceHinhAnh.JsonResponseOfListOfHinhAnh indexResult) {
            this.indexResult = indexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class storeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="store", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceHinhAnh.storeRequestBody Body;
        
        public storeRequest() {
        }
        
        public storeRequest(ClientViVuTraVinh.serviceHinhAnh.storeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class storeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DuongDan;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int NguoiTao;
        
        public storeRequestBody() {
        }
        
        public storeRequestBody(string DuongDan, int NguoiTao) {
            this.DuongDan = DuongDan;
            this.NguoiTao = NguoiTao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class storeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="storeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceHinhAnh.storeResponseBody Body;
        
        public storeResponse() {
        }
        
        public storeResponse(ClientViVuTraVinh.serviceHinhAnh.storeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class storeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceHinhAnh.JsonResponseOfString storeResult;
        
        public storeResponseBody() {
        }
        
        public storeResponseBody(ClientViVuTraVinh.serviceHinhAnh.JsonResponseOfString storeResult) {
            this.storeResult = storeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadFile", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceHinhAnh.uploadFileRequestBody Body;
        
        public uploadFileRequest() {
        }
        
        public uploadFileRequest(ClientViVuTraVinh.serviceHinhAnh.uploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class uploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] f;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        public uploadFileRequestBody() {
        }
        
        public uploadFileRequestBody(byte[] f, string fileName) {
            this.f = f;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceHinhAnh.uploadFileResponseBody Body;
        
        public uploadFileResponse() {
        }
        
        public uploadFileResponse(ClientViVuTraVinh.serviceHinhAnh.uploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class uploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceHinhAnh.JsonResponseOfString uploadFileResult;
        
        public uploadFileResponseBody() {
        }
        
        public uploadFileResponseBody(ClientViVuTraVinh.serviceHinhAnh.JsonResponseOfString uploadFileResult) {
            this.uploadFileResult = uploadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceHinhAnh.updateRequestBody Body;
        
        public updateRequest() {
        }
        
        public updateRequest(ClientViVuTraVinh.serviceHinhAnh.updateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DuongDan;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int NguoiTao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NgayTao;
        
        public updateRequestBody() {
        }
        
        public updateRequestBody(int Id, string DuongDan, int NguoiTao, string NgayTao) {
            this.Id = Id;
            this.DuongDan = DuongDan;
            this.NguoiTao = NguoiTao;
            this.NgayTao = NgayTao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceHinhAnh.updateResponseBody Body;
        
        public updateResponse() {
        }
        
        public updateResponse(ClientViVuTraVinh.serviceHinhAnh.updateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceHinhAnh.JsonResponseOfBoolean updateResult;
        
        public updateResponseBody() {
        }
        
        public updateResponseBody(ClientViVuTraVinh.serviceHinhAnh.JsonResponseOfBoolean updateResult) {
            this.updateResult = updateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delete", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceHinhAnh.deleteRequestBody Body;
        
        public deleteRequest() {
        }
        
        public deleteRequest(ClientViVuTraVinh.serviceHinhAnh.deleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        public deleteRequestBody() {
        }
        
        public deleteRequestBody(int Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceHinhAnh.deleteResponseBody Body;
        
        public deleteResponse() {
        }
        
        public deleteResponse(ClientViVuTraVinh.serviceHinhAnh.deleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceHinhAnh.JsonResponseOfBoolean deleteResult;
        
        public deleteResponseBody() {
        }
        
        public deleteResponseBody(ClientViVuTraVinh.serviceHinhAnh.JsonResponseOfBoolean deleteResult) {
            this.deleteResult = deleteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HinhAnhServiceSoapChannel : ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HinhAnhServiceSoapClient : System.ServiceModel.ClientBase<ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap>, ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap {
        
        public HinhAnhServiceSoapClient() {
        }
        
        public HinhAnhServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HinhAnhServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HinhAnhServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HinhAnhServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceHinhAnh.indexResponse ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap.index(ClientViVuTraVinh.serviceHinhAnh.indexRequest request) {
            return base.Channel.index(request);
        }
        
        public ClientViVuTraVinh.serviceHinhAnh.JsonResponseOfListOfHinhAnh index() {
            ClientViVuTraVinh.serviceHinhAnh.indexRequest inValue = new ClientViVuTraVinh.serviceHinhAnh.indexRequest();
            inValue.Body = new ClientViVuTraVinh.serviceHinhAnh.indexRequestBody();
            ClientViVuTraVinh.serviceHinhAnh.indexResponse retVal = ((ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap)(this)).index(inValue);
            return retVal.Body.indexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceHinhAnh.indexResponse> ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap.indexAsync(ClientViVuTraVinh.serviceHinhAnh.indexRequest request) {
            return base.Channel.indexAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceHinhAnh.indexResponse> indexAsync() {
            ClientViVuTraVinh.serviceHinhAnh.indexRequest inValue = new ClientViVuTraVinh.serviceHinhAnh.indexRequest();
            inValue.Body = new ClientViVuTraVinh.serviceHinhAnh.indexRequestBody();
            return ((ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap)(this)).indexAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceHinhAnh.storeResponse ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap.store(ClientViVuTraVinh.serviceHinhAnh.storeRequest request) {
            return base.Channel.store(request);
        }
        
        public ClientViVuTraVinh.serviceHinhAnh.JsonResponseOfString store(string DuongDan, int NguoiTao) {
            ClientViVuTraVinh.serviceHinhAnh.storeRequest inValue = new ClientViVuTraVinh.serviceHinhAnh.storeRequest();
            inValue.Body = new ClientViVuTraVinh.serviceHinhAnh.storeRequestBody();
            inValue.Body.DuongDan = DuongDan;
            inValue.Body.NguoiTao = NguoiTao;
            ClientViVuTraVinh.serviceHinhAnh.storeResponse retVal = ((ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap)(this)).store(inValue);
            return retVal.Body.storeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceHinhAnh.storeResponse> ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap.storeAsync(ClientViVuTraVinh.serviceHinhAnh.storeRequest request) {
            return base.Channel.storeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceHinhAnh.storeResponse> storeAsync(string DuongDan, int NguoiTao) {
            ClientViVuTraVinh.serviceHinhAnh.storeRequest inValue = new ClientViVuTraVinh.serviceHinhAnh.storeRequest();
            inValue.Body = new ClientViVuTraVinh.serviceHinhAnh.storeRequestBody();
            inValue.Body.DuongDan = DuongDan;
            inValue.Body.NguoiTao = NguoiTao;
            return ((ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap)(this)).storeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceHinhAnh.uploadFileResponse ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap.uploadFile(ClientViVuTraVinh.serviceHinhAnh.uploadFileRequest request) {
            return base.Channel.uploadFile(request);
        }
        
        public ClientViVuTraVinh.serviceHinhAnh.JsonResponseOfString uploadFile(byte[] f, string fileName) {
            ClientViVuTraVinh.serviceHinhAnh.uploadFileRequest inValue = new ClientViVuTraVinh.serviceHinhAnh.uploadFileRequest();
            inValue.Body = new ClientViVuTraVinh.serviceHinhAnh.uploadFileRequestBody();
            inValue.Body.f = f;
            inValue.Body.fileName = fileName;
            ClientViVuTraVinh.serviceHinhAnh.uploadFileResponse retVal = ((ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap)(this)).uploadFile(inValue);
            return retVal.Body.uploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceHinhAnh.uploadFileResponse> ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap.uploadFileAsync(ClientViVuTraVinh.serviceHinhAnh.uploadFileRequest request) {
            return base.Channel.uploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceHinhAnh.uploadFileResponse> uploadFileAsync(byte[] f, string fileName) {
            ClientViVuTraVinh.serviceHinhAnh.uploadFileRequest inValue = new ClientViVuTraVinh.serviceHinhAnh.uploadFileRequest();
            inValue.Body = new ClientViVuTraVinh.serviceHinhAnh.uploadFileRequestBody();
            inValue.Body.f = f;
            inValue.Body.fileName = fileName;
            return ((ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap)(this)).uploadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceHinhAnh.updateResponse ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap.update(ClientViVuTraVinh.serviceHinhAnh.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public ClientViVuTraVinh.serviceHinhAnh.JsonResponseOfBoolean update(int Id, string DuongDan, int NguoiTao, string NgayTao) {
            ClientViVuTraVinh.serviceHinhAnh.updateRequest inValue = new ClientViVuTraVinh.serviceHinhAnh.updateRequest();
            inValue.Body = new ClientViVuTraVinh.serviceHinhAnh.updateRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.DuongDan = DuongDan;
            inValue.Body.NguoiTao = NguoiTao;
            inValue.Body.NgayTao = NgayTao;
            ClientViVuTraVinh.serviceHinhAnh.updateResponse retVal = ((ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap)(this)).update(inValue);
            return retVal.Body.updateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceHinhAnh.updateResponse> ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap.updateAsync(ClientViVuTraVinh.serviceHinhAnh.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceHinhAnh.updateResponse> updateAsync(int Id, string DuongDan, int NguoiTao, string NgayTao) {
            ClientViVuTraVinh.serviceHinhAnh.updateRequest inValue = new ClientViVuTraVinh.serviceHinhAnh.updateRequest();
            inValue.Body = new ClientViVuTraVinh.serviceHinhAnh.updateRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.DuongDan = DuongDan;
            inValue.Body.NguoiTao = NguoiTao;
            inValue.Body.NgayTao = NgayTao;
            return ((ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceHinhAnh.deleteResponse ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap.delete(ClientViVuTraVinh.serviceHinhAnh.deleteRequest request) {
            return base.Channel.delete(request);
        }
        
        public ClientViVuTraVinh.serviceHinhAnh.JsonResponseOfBoolean delete(int Id) {
            ClientViVuTraVinh.serviceHinhAnh.deleteRequest inValue = new ClientViVuTraVinh.serviceHinhAnh.deleteRequest();
            inValue.Body = new ClientViVuTraVinh.serviceHinhAnh.deleteRequestBody();
            inValue.Body.Id = Id;
            ClientViVuTraVinh.serviceHinhAnh.deleteResponse retVal = ((ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap)(this)).delete(inValue);
            return retVal.Body.deleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceHinhAnh.deleteResponse> ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap.deleteAsync(ClientViVuTraVinh.serviceHinhAnh.deleteRequest request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceHinhAnh.deleteResponse> deleteAsync(int Id) {
            ClientViVuTraVinh.serviceHinhAnh.deleteRequest inValue = new ClientViVuTraVinh.serviceHinhAnh.deleteRequest();
            inValue.Body = new ClientViVuTraVinh.serviceHinhAnh.deleteRequestBody();
            inValue.Body.Id = Id;
            return ((ClientViVuTraVinh.serviceHinhAnh.HinhAnhServiceSoap)(this)).deleteAsync(inValue);
        }
    }
}
