//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientViVuTraVinh.serviceSlider {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonResponseOfListOfSlider", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class JsonResponseOfListOfSlider : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientViVuTraVinh.serviceSlider.Slider[] DataField;
        
        private int StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClientViVuTraVinh.serviceSlider.Slider[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Slider", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Slider : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnhNenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TieuDeChinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TieuDePhuField;
        
        private System.Nullable<System.DateTime> NgayTaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AnhNen {
            get {
                return this.AnhNenField;
            }
            set {
                if ((object.ReferenceEquals(this.AnhNenField, value) != true)) {
                    this.AnhNenField = value;
                    this.RaisePropertyChanged("AnhNen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TieuDeChinh {
            get {
                return this.TieuDeChinhField;
            }
            set {
                if ((object.ReferenceEquals(this.TieuDeChinhField, value) != true)) {
                    this.TieuDeChinhField = value;
                    this.RaisePropertyChanged("TieuDeChinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TieuDePhu {
            get {
                return this.TieuDePhuField;
            }
            set {
                if ((object.ReferenceEquals(this.TieuDePhuField, value) != true)) {
                    this.TieuDePhuField = value;
                    this.RaisePropertyChanged("TieuDePhu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> NgayTao {
            get {
                return this.NgayTaoField;
            }
            set {
                if ((this.NgayTaoField.Equals(value) != true)) {
                    this.NgayTaoField = value;
                    this.RaisePropertyChanged("NgayTao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonResponseOfBoolean", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class JsonResponseOfBoolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private bool DataField;
        
        private int StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="serviceSlider.SliderServiceSoap")]
    public interface SliderServiceSoap {
        
        // CODEGEN: Generating message contract since element name indexResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/index", ReplyAction="*")]
        ClientViVuTraVinh.serviceSlider.indexResponse index(ClientViVuTraVinh.serviceSlider.indexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/index", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceSlider.indexResponse> indexAsync(ClientViVuTraVinh.serviceSlider.indexRequest request);
        
        // CODEGEN: Generating message contract since element name TieuDeChinh from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/store", ReplyAction="*")]
        ClientViVuTraVinh.serviceSlider.storeResponse store(ClientViVuTraVinh.serviceSlider.storeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/store", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceSlider.storeResponse> storeAsync(ClientViVuTraVinh.serviceSlider.storeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="index", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceSlider.indexRequestBody Body;
        
        public indexRequest() {
        }
        
        public indexRequest(ClientViVuTraVinh.serviceSlider.indexRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class indexRequestBody {
        
        public indexRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="indexResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceSlider.indexResponseBody Body;
        
        public indexResponse() {
        }
        
        public indexResponse(ClientViVuTraVinh.serviceSlider.indexResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class indexResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceSlider.JsonResponseOfListOfSlider indexResult;
        
        public indexResponseBody() {
        }
        
        public indexResponseBody(ClientViVuTraVinh.serviceSlider.JsonResponseOfListOfSlider indexResult) {
            this.indexResult = indexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class storeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="store", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceSlider.storeRequestBody Body;
        
        public storeRequest() {
        }
        
        public storeRequest(ClientViVuTraVinh.serviceSlider.storeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class storeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TieuDeChinh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TieuDePhu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AnhNen;
        
        public storeRequestBody() {
        }
        
        public storeRequestBody(string TieuDeChinh, string TieuDePhu, string AnhNen) {
            this.TieuDeChinh = TieuDeChinh;
            this.TieuDePhu = TieuDePhu;
            this.AnhNen = AnhNen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class storeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="storeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceSlider.storeResponseBody Body;
        
        public storeResponse() {
        }
        
        public storeResponse(ClientViVuTraVinh.serviceSlider.storeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class storeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceSlider.JsonResponseOfBoolean storeResult;
        
        public storeResponseBody() {
        }
        
        public storeResponseBody(ClientViVuTraVinh.serviceSlider.JsonResponseOfBoolean storeResult) {
            this.storeResult = storeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SliderServiceSoapChannel : ClientViVuTraVinh.serviceSlider.SliderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SliderServiceSoapClient : System.ServiceModel.ClientBase<ClientViVuTraVinh.serviceSlider.SliderServiceSoap>, ClientViVuTraVinh.serviceSlider.SliderServiceSoap {
        
        public SliderServiceSoapClient() {
        }
        
        public SliderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SliderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SliderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SliderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceSlider.indexResponse ClientViVuTraVinh.serviceSlider.SliderServiceSoap.index(ClientViVuTraVinh.serviceSlider.indexRequest request) {
            return base.Channel.index(request);
        }
        
        public ClientViVuTraVinh.serviceSlider.JsonResponseOfListOfSlider index() {
            ClientViVuTraVinh.serviceSlider.indexRequest inValue = new ClientViVuTraVinh.serviceSlider.indexRequest();
            inValue.Body = new ClientViVuTraVinh.serviceSlider.indexRequestBody();
            ClientViVuTraVinh.serviceSlider.indexResponse retVal = ((ClientViVuTraVinh.serviceSlider.SliderServiceSoap)(this)).index(inValue);
            return retVal.Body.indexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceSlider.indexResponse> ClientViVuTraVinh.serviceSlider.SliderServiceSoap.indexAsync(ClientViVuTraVinh.serviceSlider.indexRequest request) {
            return base.Channel.indexAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceSlider.indexResponse> indexAsync() {
            ClientViVuTraVinh.serviceSlider.indexRequest inValue = new ClientViVuTraVinh.serviceSlider.indexRequest();
            inValue.Body = new ClientViVuTraVinh.serviceSlider.indexRequestBody();
            return ((ClientViVuTraVinh.serviceSlider.SliderServiceSoap)(this)).indexAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceSlider.storeResponse ClientViVuTraVinh.serviceSlider.SliderServiceSoap.store(ClientViVuTraVinh.serviceSlider.storeRequest request) {
            return base.Channel.store(request);
        }
        
        public ClientViVuTraVinh.serviceSlider.JsonResponseOfBoolean store(string TieuDeChinh, string TieuDePhu, string AnhNen) {
            ClientViVuTraVinh.serviceSlider.storeRequest inValue = new ClientViVuTraVinh.serviceSlider.storeRequest();
            inValue.Body = new ClientViVuTraVinh.serviceSlider.storeRequestBody();
            inValue.Body.TieuDeChinh = TieuDeChinh;
            inValue.Body.TieuDePhu = TieuDePhu;
            inValue.Body.AnhNen = AnhNen;
            ClientViVuTraVinh.serviceSlider.storeResponse retVal = ((ClientViVuTraVinh.serviceSlider.SliderServiceSoap)(this)).store(inValue);
            return retVal.Body.storeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceSlider.storeResponse> ClientViVuTraVinh.serviceSlider.SliderServiceSoap.storeAsync(ClientViVuTraVinh.serviceSlider.storeRequest request) {
            return base.Channel.storeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceSlider.storeResponse> storeAsync(string TieuDeChinh, string TieuDePhu, string AnhNen) {
            ClientViVuTraVinh.serviceSlider.storeRequest inValue = new ClientViVuTraVinh.serviceSlider.storeRequest();
            inValue.Body = new ClientViVuTraVinh.serviceSlider.storeRequestBody();
            inValue.Body.TieuDeChinh = TieuDeChinh;
            inValue.Body.TieuDePhu = TieuDePhu;
            inValue.Body.AnhNen = AnhNen;
            return ((ClientViVuTraVinh.serviceSlider.SliderServiceSoap)(this)).storeAsync(inValue);
        }
    }
}
