//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientViVuTraVinh.serviceDanhMuc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonResponseOfListOfDanhMuc", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class JsonResponseOfListOfDanhMuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientViVuTraVinh.serviceDanhMuc.DanhMuc[] DataField;
        
        private int StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClientViVuTraVinh.serviceDanhMuc.DanhMuc[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DanhMuc", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DanhMuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDanhMucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoTaField;
        
        private System.Nullable<System.DateTime> NgayTaoField;
        
        private System.Nullable<int> TrangThaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenDanhMuc {
            get {
                return this.TenDanhMucField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDanhMucField, value) != true)) {
                    this.TenDanhMucField = value;
                    this.RaisePropertyChanged("TenDanhMuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MoTa {
            get {
                return this.MoTaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoTaField, value) != true)) {
                    this.MoTaField = value;
                    this.RaisePropertyChanged("MoTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> NgayTao {
            get {
                return this.NgayTaoField;
            }
            set {
                if ((this.NgayTaoField.Equals(value) != true)) {
                    this.NgayTaoField = value;
                    this.RaisePropertyChanged("NgayTao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> TrangThai {
            get {
                return this.TrangThaiField;
            }
            set {
                if ((this.TrangThaiField.Equals(value) != true)) {
                    this.TrangThaiField = value;
                    this.RaisePropertyChanged("TrangThai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonResponseOfString", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class JsonResponseOfString : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        private int StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonResponseOfBoolean", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class JsonResponseOfBoolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private bool DataField;
        
        private int StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="serviceDanhMuc.DanhMucServieSoap")]
    public interface DanhMucServieSoap {
        
        // CODEGEN: Generating message contract since element name indexResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/index", ReplyAction="*")]
        ClientViVuTraVinh.serviceDanhMuc.indexResponse index(ClientViVuTraVinh.serviceDanhMuc.indexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/index", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDanhMuc.indexResponse> indexAsync(ClientViVuTraVinh.serviceDanhMuc.indexRequest request);
        
        // CODEGEN: Generating message contract since element name TenDanhMuc from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/store", ReplyAction="*")]
        ClientViVuTraVinh.serviceDanhMuc.storeResponse store(ClientViVuTraVinh.serviceDanhMuc.storeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/store", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDanhMuc.storeResponse> storeAsync(ClientViVuTraVinh.serviceDanhMuc.storeRequest request);
        
        // CODEGEN: Generating message contract since element name TenDanhMuc from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update", ReplyAction="*")]
        ClientViVuTraVinh.serviceDanhMuc.updateResponse update(ClientViVuTraVinh.serviceDanhMuc.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDanhMuc.updateResponse> updateAsync(ClientViVuTraVinh.serviceDanhMuc.updateRequest request);
        
        // CODEGEN: Generating message contract since element name deleteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete", ReplyAction="*")]
        ClientViVuTraVinh.serviceDanhMuc.deleteResponse delete(ClientViVuTraVinh.serviceDanhMuc.deleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDanhMuc.deleteResponse> deleteAsync(ClientViVuTraVinh.serviceDanhMuc.deleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="index", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDanhMuc.indexRequestBody Body;
        
        public indexRequest() {
        }
        
        public indexRequest(ClientViVuTraVinh.serviceDanhMuc.indexRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class indexRequestBody {
        
        public indexRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="indexResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDanhMuc.indexResponseBody Body;
        
        public indexResponse() {
        }
        
        public indexResponse(ClientViVuTraVinh.serviceDanhMuc.indexResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class indexResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceDanhMuc.JsonResponseOfListOfDanhMuc indexResult;
        
        public indexResponseBody() {
        }
        
        public indexResponseBody(ClientViVuTraVinh.serviceDanhMuc.JsonResponseOfListOfDanhMuc indexResult) {
            this.indexResult = indexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class storeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="store", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDanhMuc.storeRequestBody Body;
        
        public storeRequest() {
        }
        
        public storeRequest(ClientViVuTraVinh.serviceDanhMuc.storeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class storeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TenDanhMuc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MoTa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NgayTao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TrangThai;
        
        public storeRequestBody() {
        }
        
        public storeRequestBody(string TenDanhMuc, string MoTa, string NgayTao, string TrangThai) {
            this.TenDanhMuc = TenDanhMuc;
            this.MoTa = MoTa;
            this.NgayTao = NgayTao;
            this.TrangThai = TrangThai;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class storeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="storeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDanhMuc.storeResponseBody Body;
        
        public storeResponse() {
        }
        
        public storeResponse(ClientViVuTraVinh.serviceDanhMuc.storeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class storeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceDanhMuc.JsonResponseOfString storeResult;
        
        public storeResponseBody() {
        }
        
        public storeResponseBody(ClientViVuTraVinh.serviceDanhMuc.JsonResponseOfString storeResult) {
            this.storeResult = storeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDanhMuc.updateRequestBody Body;
        
        public updateRequest() {
        }
        
        public updateRequest(ClientViVuTraVinh.serviceDanhMuc.updateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TenDanhMuc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MoTa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NgayTao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TrangThai;
        
        public updateRequestBody() {
        }
        
        public updateRequestBody(int Id, string TenDanhMuc, string MoTa, string NgayTao, string TrangThai) {
            this.Id = Id;
            this.TenDanhMuc = TenDanhMuc;
            this.MoTa = MoTa;
            this.NgayTao = NgayTao;
            this.TrangThai = TrangThai;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDanhMuc.updateResponseBody Body;
        
        public updateResponse() {
        }
        
        public updateResponse(ClientViVuTraVinh.serviceDanhMuc.updateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceDanhMuc.JsonResponseOfBoolean updateResult;
        
        public updateResponseBody() {
        }
        
        public updateResponseBody(ClientViVuTraVinh.serviceDanhMuc.JsonResponseOfBoolean updateResult) {
            this.updateResult = updateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delete", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDanhMuc.deleteRequestBody Body;
        
        public deleteRequest() {
        }
        
        public deleteRequest(ClientViVuTraVinh.serviceDanhMuc.deleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        public deleteRequestBody() {
        }
        
        public deleteRequestBody(int Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDanhMuc.deleteResponseBody Body;
        
        public deleteResponse() {
        }
        
        public deleteResponse(ClientViVuTraVinh.serviceDanhMuc.deleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceDanhMuc.JsonResponseOfBoolean deleteResult;
        
        public deleteResponseBody() {
        }
        
        public deleteResponseBody(ClientViVuTraVinh.serviceDanhMuc.JsonResponseOfBoolean deleteResult) {
            this.deleteResult = deleteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DanhMucServieSoapChannel : ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DanhMucServieSoapClient : System.ServiceModel.ClientBase<ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap>, ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap {
        
        public DanhMucServieSoapClient() {
        }
        
        public DanhMucServieSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DanhMucServieSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DanhMucServieSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DanhMucServieSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceDanhMuc.indexResponse ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap.index(ClientViVuTraVinh.serviceDanhMuc.indexRequest request) {
            return base.Channel.index(request);
        }
        
        public ClientViVuTraVinh.serviceDanhMuc.JsonResponseOfListOfDanhMuc index() {
            ClientViVuTraVinh.serviceDanhMuc.indexRequest inValue = new ClientViVuTraVinh.serviceDanhMuc.indexRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDanhMuc.indexRequestBody();
            ClientViVuTraVinh.serviceDanhMuc.indexResponse retVal = ((ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap)(this)).index(inValue);
            return retVal.Body.indexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDanhMuc.indexResponse> ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap.indexAsync(ClientViVuTraVinh.serviceDanhMuc.indexRequest request) {
            return base.Channel.indexAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDanhMuc.indexResponse> indexAsync() {
            ClientViVuTraVinh.serviceDanhMuc.indexRequest inValue = new ClientViVuTraVinh.serviceDanhMuc.indexRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDanhMuc.indexRequestBody();
            return ((ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap)(this)).indexAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceDanhMuc.storeResponse ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap.store(ClientViVuTraVinh.serviceDanhMuc.storeRequest request) {
            return base.Channel.store(request);
        }
        
        public ClientViVuTraVinh.serviceDanhMuc.JsonResponseOfString store(string TenDanhMuc, string MoTa, string NgayTao, string TrangThai) {
            ClientViVuTraVinh.serviceDanhMuc.storeRequest inValue = new ClientViVuTraVinh.serviceDanhMuc.storeRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDanhMuc.storeRequestBody();
            inValue.Body.TenDanhMuc = TenDanhMuc;
            inValue.Body.MoTa = MoTa;
            inValue.Body.NgayTao = NgayTao;
            inValue.Body.TrangThai = TrangThai;
            ClientViVuTraVinh.serviceDanhMuc.storeResponse retVal = ((ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap)(this)).store(inValue);
            return retVal.Body.storeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDanhMuc.storeResponse> ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap.storeAsync(ClientViVuTraVinh.serviceDanhMuc.storeRequest request) {
            return base.Channel.storeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDanhMuc.storeResponse> storeAsync(string TenDanhMuc, string MoTa, string NgayTao, string TrangThai) {
            ClientViVuTraVinh.serviceDanhMuc.storeRequest inValue = new ClientViVuTraVinh.serviceDanhMuc.storeRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDanhMuc.storeRequestBody();
            inValue.Body.TenDanhMuc = TenDanhMuc;
            inValue.Body.MoTa = MoTa;
            inValue.Body.NgayTao = NgayTao;
            inValue.Body.TrangThai = TrangThai;
            return ((ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap)(this)).storeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceDanhMuc.updateResponse ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap.update(ClientViVuTraVinh.serviceDanhMuc.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public ClientViVuTraVinh.serviceDanhMuc.JsonResponseOfBoolean update(int Id, string TenDanhMuc, string MoTa, string NgayTao, string TrangThai) {
            ClientViVuTraVinh.serviceDanhMuc.updateRequest inValue = new ClientViVuTraVinh.serviceDanhMuc.updateRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDanhMuc.updateRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.TenDanhMuc = TenDanhMuc;
            inValue.Body.MoTa = MoTa;
            inValue.Body.NgayTao = NgayTao;
            inValue.Body.TrangThai = TrangThai;
            ClientViVuTraVinh.serviceDanhMuc.updateResponse retVal = ((ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap)(this)).update(inValue);
            return retVal.Body.updateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDanhMuc.updateResponse> ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap.updateAsync(ClientViVuTraVinh.serviceDanhMuc.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDanhMuc.updateResponse> updateAsync(int Id, string TenDanhMuc, string MoTa, string NgayTao, string TrangThai) {
            ClientViVuTraVinh.serviceDanhMuc.updateRequest inValue = new ClientViVuTraVinh.serviceDanhMuc.updateRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDanhMuc.updateRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.TenDanhMuc = TenDanhMuc;
            inValue.Body.MoTa = MoTa;
            inValue.Body.NgayTao = NgayTao;
            inValue.Body.TrangThai = TrangThai;
            return ((ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceDanhMuc.deleteResponse ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap.delete(ClientViVuTraVinh.serviceDanhMuc.deleteRequest request) {
            return base.Channel.delete(request);
        }
        
        public ClientViVuTraVinh.serviceDanhMuc.JsonResponseOfBoolean delete(int Id) {
            ClientViVuTraVinh.serviceDanhMuc.deleteRequest inValue = new ClientViVuTraVinh.serviceDanhMuc.deleteRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDanhMuc.deleteRequestBody();
            inValue.Body.Id = Id;
            ClientViVuTraVinh.serviceDanhMuc.deleteResponse retVal = ((ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap)(this)).delete(inValue);
            return retVal.Body.deleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDanhMuc.deleteResponse> ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap.deleteAsync(ClientViVuTraVinh.serviceDanhMuc.deleteRequest request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDanhMuc.deleteResponse> deleteAsync(int Id) {
            ClientViVuTraVinh.serviceDanhMuc.deleteRequest inValue = new ClientViVuTraVinh.serviceDanhMuc.deleteRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDanhMuc.deleteRequestBody();
            inValue.Body.Id = Id;
            return ((ClientViVuTraVinh.serviceDanhMuc.DanhMucServieSoap)(this)).deleteAsync(inValue);
        }
    }
}
