//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientViVuTraVinh.serviceDiaDiem {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonResponseOfListOfDiaDiem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class JsonResponseOfListOfDiaDiem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientViVuTraVinh.serviceDiaDiem.DiaDiem[] DataField;
        
        private int StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClientViVuTraVinh.serviceDiaDiem.DiaDiem[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiaDiem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DiaDiem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.Nullable<int> DanhMucIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HinhAnhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDiaDiemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoTaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        private System.Nullable<int> NguoiTaoField;
        
        private System.Nullable<int> LuotXemField;
        
        private System.Nullable<int> LaNoiBatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrangThaiField;
        
        private System.Nullable<System.DateTime> NgayTaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IframeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NgonNguField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientViVuTraVinh.serviceDiaDiem.DanhMuc DanhMucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientViVuTraVinh.serviceDiaDiem.TaiKhoan TaiKhoanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> DanhMucId {
            get {
                return this.DanhMucIdField;
            }
            set {
                if ((this.DanhMucIdField.Equals(value) != true)) {
                    this.DanhMucIdField = value;
                    this.RaisePropertyChanged("DanhMucId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HinhAnh {
            get {
                return this.HinhAnhField;
            }
            set {
                if ((object.ReferenceEquals(this.HinhAnhField, value) != true)) {
                    this.HinhAnhField = value;
                    this.RaisePropertyChanged("HinhAnh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TenDiaDiem {
            get {
                return this.TenDiaDiemField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDiaDiemField, value) != true)) {
                    this.TenDiaDiemField = value;
                    this.RaisePropertyChanged("TenDiaDiem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MoTa {
            get {
                return this.MoTaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoTaField, value) != true)) {
                    this.MoTaField = value;
                    this.RaisePropertyChanged("MoTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NoiDung {
            get {
                return this.NoiDungField;
            }
            set {
                if ((object.ReferenceEquals(this.NoiDungField, value) != true)) {
                    this.NoiDungField = value;
                    this.RaisePropertyChanged("NoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> NguoiTao {
            get {
                return this.NguoiTaoField;
            }
            set {
                if ((this.NguoiTaoField.Equals(value) != true)) {
                    this.NguoiTaoField = value;
                    this.RaisePropertyChanged("NguoiTao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> LuotXem {
            get {
                return this.LuotXemField;
            }
            set {
                if ((this.LuotXemField.Equals(value) != true)) {
                    this.LuotXemField = value;
                    this.RaisePropertyChanged("LuotXem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<int> LaNoiBat {
            get {
                return this.LaNoiBatField;
            }
            set {
                if ((this.LaNoiBatField.Equals(value) != true)) {
                    this.LaNoiBatField = value;
                    this.RaisePropertyChanged("LaNoiBat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string TrangThai {
            get {
                return this.TrangThaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TrangThaiField, value) != true)) {
                    this.TrangThaiField = value;
                    this.RaisePropertyChanged("TrangThai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<System.DateTime> NgayTao {
            get {
                return this.NgayTaoField;
            }
            set {
                if ((this.NgayTaoField.Equals(value) != true)) {
                    this.NgayTaoField = value;
                    this.RaisePropertyChanged("NgayTao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Iframe {
            get {
                return this.IframeField;
            }
            set {
                if ((object.ReferenceEquals(this.IframeField, value) != true)) {
                    this.IframeField = value;
                    this.RaisePropertyChanged("Iframe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string NgonNgu {
            get {
                return this.NgonNguField;
            }
            set {
                if ((object.ReferenceEquals(this.NgonNguField, value) != true)) {
                    this.NgonNguField = value;
                    this.RaisePropertyChanged("NgonNgu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public ClientViVuTraVinh.serviceDiaDiem.DanhMuc DanhMuc {
            get {
                return this.DanhMucField;
            }
            set {
                if ((object.ReferenceEquals(this.DanhMucField, value) != true)) {
                    this.DanhMucField = value;
                    this.RaisePropertyChanged("DanhMuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public ClientViVuTraVinh.serviceDiaDiem.TaiKhoan TaiKhoan {
            get {
                return this.TaiKhoanField;
            }
            set {
                if ((object.ReferenceEquals(this.TaiKhoanField, value) != true)) {
                    this.TaiKhoanField = value;
                    this.RaisePropertyChanged("TaiKhoan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DanhMuc", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DanhMuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDanhMucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoTaField;
        
        private System.Nullable<System.DateTime> NgayTaoField;
        
        private System.Nullable<int> TrangThaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenDanhMuc {
            get {
                return this.TenDanhMucField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDanhMucField, value) != true)) {
                    this.TenDanhMucField = value;
                    this.RaisePropertyChanged("TenDanhMuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MoTa {
            get {
                return this.MoTaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoTaField, value) != true)) {
                    this.MoTaField = value;
                    this.RaisePropertyChanged("MoTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> NgayTao {
            get {
                return this.NgayTaoField;
            }
            set {
                if ((this.NgayTaoField.Equals(value) != true)) {
                    this.NgayTaoField = value;
                    this.RaisePropertyChanged("NgayTao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> TrangThai {
            get {
                return this.TrangThaiField;
            }
            set {
                if ((this.TrangThaiField.Equals(value) != true)) {
                    this.TrangThaiField = value;
                    this.RaisePropertyChanged("TrangThai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaiKhoan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TaiKhoan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDangNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoDienThoaiField;
        
        private System.Nullable<int> RoleField;
        
        private System.Nullable<int> StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenDangNhap {
            get {
                return this.TenDangNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDangNhapField, value) != true)) {
                    this.TenDangNhapField = value;
                    this.RaisePropertyChanged("TenDangNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SoDienThoai {
            get {
                return this.SoDienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoDienThoaiField, value) != true)) {
                    this.SoDienThoaiField = value;
                    this.RaisePropertyChanged("SoDienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonResponseOfString", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class JsonResponseOfString : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        private int StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonResponseOfBoolean", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class JsonResponseOfBoolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private bool DataField;
        
        private int StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="serviceDiaDiem.DiaDiemServiceSoap")]
    public interface DiaDiemServiceSoap {
        
        // CODEGEN: Generating message contract since element name indexResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/index", ReplyAction="*")]
        ClientViVuTraVinh.serviceDiaDiem.indexResponse index(ClientViVuTraVinh.serviceDiaDiem.indexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/index", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.indexResponse> indexAsync(ClientViVuTraVinh.serviceDiaDiem.indexRequest request);
        
        // CODEGEN: Generating message contract since element name indexJsonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/indexJson", ReplyAction="*")]
        ClientViVuTraVinh.serviceDiaDiem.indexJsonResponse indexJson(ClientViVuTraVinh.serviceDiaDiem.indexJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/indexJson", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.indexJsonResponse> indexJsonAsync(ClientViVuTraVinh.serviceDiaDiem.indexJsonRequest request);
        
        // CODEGEN: Generating message contract since element name HinhAnh from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/store", ReplyAction="*")]
        ClientViVuTraVinh.serviceDiaDiem.storeResponse store(ClientViVuTraVinh.serviceDiaDiem.storeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/store", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.storeResponse> storeAsync(ClientViVuTraVinh.serviceDiaDiem.storeRequest request);
        
        // CODEGEN: Generating message contract since element name HinhAnh from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update", ReplyAction="*")]
        ClientViVuTraVinh.serviceDiaDiem.updateResponse update(ClientViVuTraVinh.serviceDiaDiem.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.updateResponse> updateAsync(ClientViVuTraVinh.serviceDiaDiem.updateRequest request);
        
        // CODEGEN: Generating message contract since element name ThemBinhLuanResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemBinhLuan", ReplyAction="*")]
        ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanResponse ThemBinhLuan(ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemBinhLuan", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanResponse> ThemBinhLuanAsync(ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanRequest request);
        
        // CODEGEN: Generating message contract since element name deleteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete", ReplyAction="*")]
        ClientViVuTraVinh.serviceDiaDiem.deleteResponse delete(ClientViVuTraVinh.serviceDiaDiem.deleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.deleteResponse> deleteAsync(ClientViVuTraVinh.serviceDiaDiem.deleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="index", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.indexRequestBody Body;
        
        public indexRequest() {
        }
        
        public indexRequest(ClientViVuTraVinh.serviceDiaDiem.indexRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class indexRequestBody {
        
        public indexRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="indexResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.indexResponseBody Body;
        
        public indexResponse() {
        }
        
        public indexResponse(ClientViVuTraVinh.serviceDiaDiem.indexResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class indexResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfListOfDiaDiem indexResult;
        
        public indexResponseBody() {
        }
        
        public indexResponseBody(ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfListOfDiaDiem indexResult) {
            this.indexResult = indexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indexJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="indexJson", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.indexJsonRequestBody Body;
        
        public indexJsonRequest() {
        }
        
        public indexJsonRequest(ClientViVuTraVinh.serviceDiaDiem.indexJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class indexJsonRequestBody {
        
        public indexJsonRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indexJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="indexJsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.indexJsonResponseBody Body;
        
        public indexJsonResponse() {
        }
        
        public indexJsonResponse(ClientViVuTraVinh.serviceDiaDiem.indexJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class indexJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfString indexJsonResult;
        
        public indexJsonResponseBody() {
        }
        
        public indexJsonResponseBody(ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfString indexJsonResult) {
            this.indexJsonResult = indexJsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class storeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="store", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.storeRequestBody Body;
        
        public storeRequest() {
        }
        
        public storeRequest(ClientViVuTraVinh.serviceDiaDiem.storeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class storeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HinhAnh;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DanhMucId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DiaChi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TenDiaDiem;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int NguoiTao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MoTa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string NoiDung;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NgayTao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TrangThai;
        
        public storeRequestBody() {
        }
        
        public storeRequestBody(string HinhAnh, int DanhMucId, string DiaChi, string TenDiaDiem, int NguoiTao, string MoTa, string NoiDung, string NgayTao, string TrangThai) {
            this.HinhAnh = HinhAnh;
            this.DanhMucId = DanhMucId;
            this.DiaChi = DiaChi;
            this.TenDiaDiem = TenDiaDiem;
            this.NguoiTao = NguoiTao;
            this.MoTa = MoTa;
            this.NoiDung = NoiDung;
            this.NgayTao = NgayTao;
            this.TrangThai = TrangThai;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class storeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="storeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.storeResponseBody Body;
        
        public storeResponse() {
        }
        
        public storeResponse(ClientViVuTraVinh.serviceDiaDiem.storeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class storeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfString storeResult;
        
        public storeResponseBody() {
        }
        
        public storeResponseBody(ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfString storeResult) {
            this.storeResult = storeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.updateRequestBody Body;
        
        public updateRequest() {
        }
        
        public updateRequest(ClientViVuTraVinh.serviceDiaDiem.updateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HinhAnh;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int DanhMucId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DiaChi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TenDiaDiem;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int NguoiTao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MoTa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NgayTao;
        
        public updateRequestBody() {
        }
        
        public updateRequestBody(int Id, string HinhAnh, int DanhMucId, string DiaChi, string TenDiaDiem, int NguoiTao, string MoTa, string NgayTao) {
            this.Id = Id;
            this.HinhAnh = HinhAnh;
            this.DanhMucId = DanhMucId;
            this.DiaChi = DiaChi;
            this.TenDiaDiem = TenDiaDiem;
            this.NguoiTao = NguoiTao;
            this.MoTa = MoTa;
            this.NgayTao = NgayTao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.updateResponseBody Body;
        
        public updateResponse() {
        }
        
        public updateResponse(ClientViVuTraVinh.serviceDiaDiem.updateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfBoolean updateResult;
        
        public updateResponseBody() {
        }
        
        public updateResponseBody(ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfBoolean updateResult) {
            this.updateResult = updateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ThemBinhLuanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ThemBinhLuan", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanRequestBody Body;
        
        public ThemBinhLuanRequest() {
        }
        
        public ThemBinhLuanRequest(ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ThemBinhLuanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int khachHangId;
        
        public ThemBinhLuanRequestBody() {
        }
        
        public ThemBinhLuanRequestBody(int khachHangId) {
            this.khachHangId = khachHangId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ThemBinhLuanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ThemBinhLuanResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanResponseBody Body;
        
        public ThemBinhLuanResponse() {
        }
        
        public ThemBinhLuanResponse(ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ThemBinhLuanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfBoolean ThemBinhLuanResult;
        
        public ThemBinhLuanResponseBody() {
        }
        
        public ThemBinhLuanResponseBody(ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfBoolean ThemBinhLuanResult) {
            this.ThemBinhLuanResult = ThemBinhLuanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delete", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.deleteRequestBody Body;
        
        public deleteRequest() {
        }
        
        public deleteRequest(ClientViVuTraVinh.serviceDiaDiem.deleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        public deleteRequestBody() {
        }
        
        public deleteRequestBody(int Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.deleteResponseBody Body;
        
        public deleteResponse() {
        }
        
        public deleteResponse(ClientViVuTraVinh.serviceDiaDiem.deleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfBoolean deleteResult;
        
        public deleteResponseBody() {
        }
        
        public deleteResponseBody(ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfBoolean deleteResult) {
            this.deleteResult = deleteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DiaDiemServiceSoapChannel : ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiaDiemServiceSoapClient : System.ServiceModel.ClientBase<ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap>, ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap {
        
        public DiaDiemServiceSoapClient() {
        }
        
        public DiaDiemServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiaDiemServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiaDiemServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiaDiemServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceDiaDiem.indexResponse ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap.index(ClientViVuTraVinh.serviceDiaDiem.indexRequest request) {
            return base.Channel.index(request);
        }
        
        public ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfListOfDiaDiem index() {
            ClientViVuTraVinh.serviceDiaDiem.indexRequest inValue = new ClientViVuTraVinh.serviceDiaDiem.indexRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDiaDiem.indexRequestBody();
            ClientViVuTraVinh.serviceDiaDiem.indexResponse retVal = ((ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap)(this)).index(inValue);
            return retVal.Body.indexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.indexResponse> ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap.indexAsync(ClientViVuTraVinh.serviceDiaDiem.indexRequest request) {
            return base.Channel.indexAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.indexResponse> indexAsync() {
            ClientViVuTraVinh.serviceDiaDiem.indexRequest inValue = new ClientViVuTraVinh.serviceDiaDiem.indexRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDiaDiem.indexRequestBody();
            return ((ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap)(this)).indexAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceDiaDiem.indexJsonResponse ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap.indexJson(ClientViVuTraVinh.serviceDiaDiem.indexJsonRequest request) {
            return base.Channel.indexJson(request);
        }
        
        public ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfString indexJson() {
            ClientViVuTraVinh.serviceDiaDiem.indexJsonRequest inValue = new ClientViVuTraVinh.serviceDiaDiem.indexJsonRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDiaDiem.indexJsonRequestBody();
            ClientViVuTraVinh.serviceDiaDiem.indexJsonResponse retVal = ((ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap)(this)).indexJson(inValue);
            return retVal.Body.indexJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.indexJsonResponse> ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap.indexJsonAsync(ClientViVuTraVinh.serviceDiaDiem.indexJsonRequest request) {
            return base.Channel.indexJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.indexJsonResponse> indexJsonAsync() {
            ClientViVuTraVinh.serviceDiaDiem.indexJsonRequest inValue = new ClientViVuTraVinh.serviceDiaDiem.indexJsonRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDiaDiem.indexJsonRequestBody();
            return ((ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap)(this)).indexJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceDiaDiem.storeResponse ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap.store(ClientViVuTraVinh.serviceDiaDiem.storeRequest request) {
            return base.Channel.store(request);
        }
        
        public ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfString store(string HinhAnh, int DanhMucId, string DiaChi, string TenDiaDiem, int NguoiTao, string MoTa, string NoiDung, string NgayTao, string TrangThai) {
            ClientViVuTraVinh.serviceDiaDiem.storeRequest inValue = new ClientViVuTraVinh.serviceDiaDiem.storeRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDiaDiem.storeRequestBody();
            inValue.Body.HinhAnh = HinhAnh;
            inValue.Body.DanhMucId = DanhMucId;
            inValue.Body.DiaChi = DiaChi;
            inValue.Body.TenDiaDiem = TenDiaDiem;
            inValue.Body.NguoiTao = NguoiTao;
            inValue.Body.MoTa = MoTa;
            inValue.Body.NoiDung = NoiDung;
            inValue.Body.NgayTao = NgayTao;
            inValue.Body.TrangThai = TrangThai;
            ClientViVuTraVinh.serviceDiaDiem.storeResponse retVal = ((ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap)(this)).store(inValue);
            return retVal.Body.storeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.storeResponse> ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap.storeAsync(ClientViVuTraVinh.serviceDiaDiem.storeRequest request) {
            return base.Channel.storeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.storeResponse> storeAsync(string HinhAnh, int DanhMucId, string DiaChi, string TenDiaDiem, int NguoiTao, string MoTa, string NoiDung, string NgayTao, string TrangThai) {
            ClientViVuTraVinh.serviceDiaDiem.storeRequest inValue = new ClientViVuTraVinh.serviceDiaDiem.storeRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDiaDiem.storeRequestBody();
            inValue.Body.HinhAnh = HinhAnh;
            inValue.Body.DanhMucId = DanhMucId;
            inValue.Body.DiaChi = DiaChi;
            inValue.Body.TenDiaDiem = TenDiaDiem;
            inValue.Body.NguoiTao = NguoiTao;
            inValue.Body.MoTa = MoTa;
            inValue.Body.NoiDung = NoiDung;
            inValue.Body.NgayTao = NgayTao;
            inValue.Body.TrangThai = TrangThai;
            return ((ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap)(this)).storeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceDiaDiem.updateResponse ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap.update(ClientViVuTraVinh.serviceDiaDiem.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfBoolean update(int Id, string HinhAnh, int DanhMucId, string DiaChi, string TenDiaDiem, int NguoiTao, string MoTa, string NgayTao) {
            ClientViVuTraVinh.serviceDiaDiem.updateRequest inValue = new ClientViVuTraVinh.serviceDiaDiem.updateRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDiaDiem.updateRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.HinhAnh = HinhAnh;
            inValue.Body.DanhMucId = DanhMucId;
            inValue.Body.DiaChi = DiaChi;
            inValue.Body.TenDiaDiem = TenDiaDiem;
            inValue.Body.NguoiTao = NguoiTao;
            inValue.Body.MoTa = MoTa;
            inValue.Body.NgayTao = NgayTao;
            ClientViVuTraVinh.serviceDiaDiem.updateResponse retVal = ((ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap)(this)).update(inValue);
            return retVal.Body.updateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.updateResponse> ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap.updateAsync(ClientViVuTraVinh.serviceDiaDiem.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.updateResponse> updateAsync(int Id, string HinhAnh, int DanhMucId, string DiaChi, string TenDiaDiem, int NguoiTao, string MoTa, string NgayTao) {
            ClientViVuTraVinh.serviceDiaDiem.updateRequest inValue = new ClientViVuTraVinh.serviceDiaDiem.updateRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDiaDiem.updateRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.HinhAnh = HinhAnh;
            inValue.Body.DanhMucId = DanhMucId;
            inValue.Body.DiaChi = DiaChi;
            inValue.Body.TenDiaDiem = TenDiaDiem;
            inValue.Body.NguoiTao = NguoiTao;
            inValue.Body.MoTa = MoTa;
            inValue.Body.NgayTao = NgayTao;
            return ((ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanResponse ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap.ThemBinhLuan(ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanRequest request) {
            return base.Channel.ThemBinhLuan(request);
        }
        
        public ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfBoolean ThemBinhLuan(int khachHangId) {
            ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanRequest inValue = new ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanRequestBody();
            inValue.Body.khachHangId = khachHangId;
            ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanResponse retVal = ((ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap)(this)).ThemBinhLuan(inValue);
            return retVal.Body.ThemBinhLuanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanResponse> ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap.ThemBinhLuanAsync(ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanRequest request) {
            return base.Channel.ThemBinhLuanAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanResponse> ThemBinhLuanAsync(int khachHangId) {
            ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanRequest inValue = new ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDiaDiem.ThemBinhLuanRequestBody();
            inValue.Body.khachHangId = khachHangId;
            return ((ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap)(this)).ThemBinhLuanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientViVuTraVinh.serviceDiaDiem.deleteResponse ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap.delete(ClientViVuTraVinh.serviceDiaDiem.deleteRequest request) {
            return base.Channel.delete(request);
        }
        
        public ClientViVuTraVinh.serviceDiaDiem.JsonResponseOfBoolean delete(int Id) {
            ClientViVuTraVinh.serviceDiaDiem.deleteRequest inValue = new ClientViVuTraVinh.serviceDiaDiem.deleteRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDiaDiem.deleteRequestBody();
            inValue.Body.Id = Id;
            ClientViVuTraVinh.serviceDiaDiem.deleteResponse retVal = ((ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap)(this)).delete(inValue);
            return retVal.Body.deleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.deleteResponse> ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap.deleteAsync(ClientViVuTraVinh.serviceDiaDiem.deleteRequest request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientViVuTraVinh.serviceDiaDiem.deleteResponse> deleteAsync(int Id) {
            ClientViVuTraVinh.serviceDiaDiem.deleteRequest inValue = new ClientViVuTraVinh.serviceDiaDiem.deleteRequest();
            inValue.Body = new ClientViVuTraVinh.serviceDiaDiem.deleteRequestBody();
            inValue.Body.Id = Id;
            return ((ClientViVuTraVinh.serviceDiaDiem.DiaDiemServiceSoap)(this)).deleteAsync(inValue);
        }
    }
}
